#' Better Rprofile
#' 
#' Replace the project-specific .Rprofile generated by renv with a template
#' that solves my headaches with VSCode and renv.
#' @export
better_rprofile <- function() {
  contents <- 'Sys.setenv(
  RENV_CONFIG_RSPM_ENABLED = FALSE,
  RENV_CONFIG_SANDBOX_ENABLED = FALSE
)

if (requireNamespace("rprofile", quietly = TRUE)) {
  rprofile::load(dev = quote(reload()))
} else {
  source("renv/activate.R")
}'
  writeLines(contents, con = ".Rprofile")
}
